version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MALLOC_INTERVAL_MILLISECOND=1000
      - MALLOC_INTERVAL_MIBIBYTE=1024
      - LOG_FILE_PATH=/var/log/myapp/log
    volumes:
      - ./log:/var/log/myapp:rw
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    privileged: true
    command: ["/usr/bin/cadvisor", "-logtostderr"]
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
